name: gui_test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: SetupWorkspace
          run: |
            cd ci
            ./gui.sh
            ./guiTest.sh

        - name: Build
          run: |
            mkdir build
            cd build
            cmake .. -DGUI_BUILD=ON -DGUI_TEST_BUILD=ON
            make

        - name: Test
          run: |
            cd build/bin
            ./gui_test